apiVersion: v2
name: portal-backend
description: Helm chart for Catena-X Portal backend
type: application
version: 0.6.1
appVersion: 0.6.0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: pgadmin4.enabled
    name: pgadmin4
    repository: https://helm.runix.net
    version: 1.11.x
