apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-backend-pen
spec:
  destination:
    namespace: product-portal-pen
    server: 'https://kubernetes.default.svc'
  source:
    path: chart/portal-backend
    repoURL: 'https://github.com/catenax-ng/product-portal-cd.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f values-pen.yaml'
  project: project-portal