domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: dev_48f6df0807e978730a63b93dc62988c4ab2c99bd

assets:
  image: "ghcr.io/catenax-ng/product-portal-common-assets:dev"

registration:
  image: "ghcr.io/catenax-ng/product-portal-frontend-registration:dev"

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
