name: "portal-pen"
domain: "dev.demo.catena-x.net"

portal:
  image: "ghcr.io/catenax-ng/product-portal-frontend:main"

assets:
  image: "ghcr.io/catenax-ng/product-portal-common-assets:main"

registration:
  image: "ghcr.io/catenax-ng/product-portal-frontend-registration:main"

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
