apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.corsOrigins }}
spec:
  tls:
  - hosts:
    - {{ .Values.name }}.{{ .Values.domain }}
    secretName: {{ .Values.name }}.{{ .Values.domain }}-tls
  rules:
  - host: {{ .Values.name }}.{{ .Values.domain }}
    http:
      paths:

      - path: /api/registration
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.registration.name }}
            port:
              number: {{ .Values.portService }}

      - path: /api/administration
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.administration.name }}
            port:
              number: {{ .Values.portService }}

      - path: /api/notification
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.notification.name }}
            port:
              number: {{ .Values.portService }}

      - path: /api/provisioning
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.provisioning.name }}
            port:
              number: {{ .Values.portService }}

      - path: /api/apps
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appmarketplace.name }}
            port:
              number: {{ .Values.portService }}
