apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.portalmigrations.secret.path }}
  name: {{ .Values.portalmigrations.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  appsettings.json: <appsettings.json>