apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.registration.secret.path }}
  name: {{ .Values.registration.secret.name }}
  namespace: {{ .Release.Name }}
type: Opaque
data:
  appsettings.json: <appsettings.json>