domain: dev.demo.catena-x.net
corsOrigins: http://localhost:3000, https://*.dev.demo.catena-x.net

postgresql:
  secret:
    pathinit: portal/data/dev/postgres
    pathinitdbuser: portal/data/dev/postgres-db-user

registration:
  image:
    registrationtag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/registration

administration:
  image:
    administrationtag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/administration

provisioning:
  image:
    provisioningtag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/provisioning

appmarketplace:
  image:
    appmarketplacetag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/appmarketplace

portalmigrations:
  image:
    portalmigrationstag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/portal-migrations

portalmaintenance:
  image:
    portalmaintenancetag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/portal-maintenance

notification:
  image:
    notificationtag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/dev/pgadmin4
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: portal-pgadmin4.dev.demo.catena-x.net-tls