apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.portalmaintenance.name }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Values.portalmaintenance.name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.portalmaintenance.image.name }}:{{ .Values.portalmaintenance.image.portalmaintenancetag | default .Chart.AppVersion }}"
            imagePullPolicy: "Always"
            ports:
            - containerPort: {{ .Values.portContainer }}
            env:
            - name: "DOTNET_ENVIRONMENT"
              value: "Kubernetes"
            volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
          volumes:
          - name: secrets
            secret:
              secretName: {{ .Values.portalmaintenance.secret.name }}
